sonar.projectKey=vua

sonar.sources=src,root
sonar.tests=src,root

sonar.token=sqp_9585e4059bdf7e4808553083d7681ffeebe70493
sonar.host.url=http://localhost:9000/

sonar.java.binaries=out
sonar.java.libraries=lib

sonar.test.inclusions=**/*FunctionTest.java,**/*FunctionalZAP.java
